import enum

class ApplicationStatus(enum.Enum):
    APPLICATION = "APPLICATION"
    SCREENING = "SCREENING"
    RH_INTERVIEW = "RH_INTERVIEW"
    TECHNICAL_INTERVIEW = "TECHNICAL_INTERVIEW"
    OFFER = "OFFER"
    HIRED = "HIRED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"